Auth- and RoleGuard
CUMGroup/AMOGUS pull request #109
Opened 2023-05-07 13:57 UTC by Annalytic-programming

2023-05-07 14:00 UTC, Annalytic-programming commented on src/ui/src/app/core/services/authentication/authentication.service.ts
Maybe we can delete either isLoggedIn-Method or isAuthenticated-Method.
isAuthenticated searches for the explicit User Object inside the id-token if it is here. So imo it is slightly better then just looking for the token itself.

2023-05-07 14:02 UTC, Annalytic-programming commented on src/ui/src/app/shared/components/nav-bar/nav-bar.component.html
The Teacher-View icon can now only be seen, if the user has the Teacher role.

2023-05-07 19:39 UTC, AlexMi-Ha commented
Conflict bitte noch lösen

2023-05-07 20:07 UTC, AlexMi-Ha requested changes

2023-05-07 20:07 UTC, AlexMi-Ha commented on src/ui/src/app/core/services/authentication/authentication.service.ts
> +    if (this.getRoles().includes('Teacher') || this.getRoles().includes('Admin')){
warum hier nicht hasRole verwendet?

2023-05-07 20:07 UTC, AlexMi-Ha commented on src/ui/src/app/core/services/authentication/role-guard.service.ts
> +      if (!this.authService.hasRole('Teacher') || !this.authService.hasRole('Admin')) {
warum hier nicht isTeacherOrAdmin?

2023-05-07 20:07 UTC, AlexMi-Ha commented on src/ui/src/app/modules/user/user-routing.module.ts
> +    canActivate: [AuthGuardService, RoleGuardService]
warum muss man für die game-selection admin haben?

2023-05-07 20:07 UTC, AlexMi-Ha commented on src/ui/src/app/core/services/authentication/role-guard.service.ts
> +      if (!this.authService.hasRole('Teacher') || !this.authService.hasRole('Admin')) {
Im Backend
AMOGUS.Core/Centralization/UserRoles.cs müsste noch die Rolle "Moderator" zu "Teacher geändert werden.
(und natürlich der AuthServiceTest Unit Test angepasst werden)

Oder hier im Frontend die "Teacher" role auch zu "Moderator" umbenennen

2023-05-09 07:41 UTC, AlexMi-Ha requested changes

2023-05-09 07:41 UTC, AlexMi-Ha commented on package.json
> +  "dependencies": {
big nono

2023-05-09 07:41 UTC, AlexMi-Ha commented on package-lock.json
big nono

2023-05-09 08:13 UTC, AlexMi-Ha requested changes

2023-05-09 08:13 UTC, AlexMi-Ha commented on src/ui/src/app/modules/user/user-routing.module.ts
> +    canActivate: [RoleGuardService]
AuthGuard

2023-05-09 08:35 UTC, AlexMi-Ha approved these changes
pasta

2023-05-09 08:35 UTC, merged