Styling / HttpInterceptor
CUMGroup/AMOGUS pull request #69
Opened 2023-04-12 09:00 UTC by WachtelHD

2023-04-12 12:48 UTC, AlexMi-Ha requested changes

2023-04-12 12:48 UTC, AlexMi-Ha commented on src/ui/src/app/modules/user/pages/game-selection/game-selection.component.ts
> +    this.http.get('https://example.com/api/things')
was isn des 🗿

2023-04-12 14:42 UTC, WachtelHD commented on src/ui/src/app/modules/user/pages/game-selection/game-selection.component.ts
> +    this.http.get('https://example.com/api/things')
Oh war zum testen der request XD

2023-04-13 14:13 UTC, AlexMi-Ha approved these changes

2023-04-13 14:13 UTC, merged